### ISSUE TITLE
please add libpq-dev and sqlite_devel to /cvmfs/singularity.opensciencegrid.org/fermilab/fnal-dev-sl7:latest

### ISSUE THREAD

**Issue by goodenou** [glideinWMS/containers#33]
DUNE is requesting to add postgresql-devel and sqlite-devel to the development container in INC000001172471.

**Comment by mambelli** [comment]
Installed. Even if libpq-devel is not found in the RPM list ....

**Comment by vitodb** [comment]
The actual package needed was `postgresql-devel` that provides `/usr/include/libpq-fe.h`.
This package is already included in the container.
