### ISSUE TITLE
please add git-lfs rpm to /cvmfs/singularity.opensciencegrid.org/fermilab/fnal-dev-sl7:latest

### ISSUE THREAD

**Issue by goodenou** [glideinWMS/containers#39]
gm2 uses Git Large File Service for some of its repos that it recently migrated to GitHub. We need to be able to use the Large File Service in our workflows inside the SL7 container. Will you please add the git-lfs rpm to the development container?

**Comment by mambelli** [comment]
Fixed on 5/22, e0b9c85d
