### ISSUE TITLE
Urgent: distribute `perl-File-Copy*` packages with `/cvmfs/singularity.opensciencegrid.org/fermilab/fnal-wn-el9:latest`

### ISSUE THREAD

**Issue by riccardodimaria** [glideinWMS/containers#50]
Good morning,
I hope this finds you OK.

CSCS WLCG-Tier2 site is serving ATLAS, CMS, and LHCb VOs, hosted on HPC resources. 
For this reason, WLCG pilots and jobs cannot run directly on the node, but a singularity container is spawned as a dedicated environment to be used by the jobs. `/cvmfs/singularity.opensciencegrid.org/fermilab/fnal-wn-*` is used as a base docker image.

CSCS has recently migrated from `/cvmfs/singularity.opensciencegrid.org/fermilab/fnal-wn-sl7:latest` to `/cvmfs/singularity.opensciencegrid.org/fermilab/fnal-wn-el9:latest`.
Both images are missing `perl-File-Copy*` packages.

After a long maintenance/downtime period at CSCS, production has restarted with CMS VO severely affected. ATLAS and LHCb are running OK, and they use configuration and environment shared among all VOs.

Debug has been ongoing on several levels:
- https://ggus.eu/index.php?mode=ticket_info&ticket_id=167495
- https://mattermost.web.cern.ch/cms-o-and-c/pl/y9jrgumfb7gw8khgcqhrj17crr
- https://mattermost.web.cern.ch/cms-o-and-c/pl/z8czque49fr78pr7cq6g5iqmic

Colleagues from SubmissionInfrastructure are suggesting having `perl-File-Copy` available on the WNs as CMS pilots cannot find them. For us, this means having the aforementioned packages available in `/cvmfs/singularity.opensciencegrid.org/fermilab/fnal-wn-el9:latest`.
I have already mentioned those packages are missing from `/cvmfs/singularity.opensciencegrid.org/fermilab/fnal-wn-sl7:latest` as well, but may you please add them to the `el9` image to disprove this and remove the uncertainty during the debug process?

Best regards,
Riccardo

**Comment by mambelli** [comment]
Other packages that I see in the SL7 image are:
```
perl perl-autodie perl-Carp perl-constant perl-Data-Dumper perl-Digest perl-Digest-SHA perl-Exporter perl-File-Path perl-File-Temp perl-Getopt-Long perl-libs perl-PathTools perl-Scalar-List-Utils \
    perl-JSON perl-Archive-Tar perl-IO-Compress \
```
any of these is needed?
